name: satip_dev

channels:
  - conda-forge
  - coecms
  - auto
  
dependencies:
  - python>=3.7
  - pytest
  - pytables
  - pandas
  - matplotlib
  - jupyterlab
  - ipympl
  - nodejs
  - satpy
  - netCDF4
  - xarray
  - cartopy
  - pyproj
  - pyinterp
  - geopandas
  - rasterio
  - pillow  
  - gdal
  - lxml
  - tabulate
  - python-dotenv
  - xmltodict
  - dataset
  - seaborn
  - mkdocs-material
  - twine
  - gcsfs
  - zarr
  - dagster
  - dagit
  - mkdocs
  - mkdocs-material
  - typer
  - pip
  
  - pip:
      - -e .
      - dagster-airflow
      - nbdev
      - ipypb
      - feautils
      - slack-logger
      - mkdocs-material-extensions
      - mkdocstrings
      - google-cloud-storage
      - configparser
      - pandas_gbq
      - junix