name: continuous_retrieval
on: workflow_dispatch

jobs:
  miniconda:
    name: Miniconda ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: ["ubuntu-latest"]
            
    steps:
      - name: Load in repo
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
    
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
        
      - name: Running pipeline
        shell: bash -l {0}
        env: 
          USER_KEY: ${{ secrets.USER_KEY }}
          USER_SECRET: ${{ secrets.USER_SECRET }}
          SLACK_ID: ${{ secrets.SLACK_ID }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install dagit
          dagster pipeline execute -m satip.mario -c pipeline_inputs.yaml
